# WARNING
# YOU MUST CHANGE THE NAME OF THIS FILE to 'config.py'
# FOR TRADEBOX TO RUN

# ENVIRONMENT = 'production' or ENVIRONMENT = 'development'
ENVIRONMENT = ''

# ENTER ROBINHOOD USERNAME AND PASSWORD
ROBINHOOD_USERNAME = ''
ROBINHOOD_PASSWORD = ''

SMTP_USERNAME = ''
SMTP_PASSWORD = ''
SMTP_SERVER = ''
SMTP_PORT = 465  # port for Gmail SSL if using Gmail's SMTP servers
NOTIFICATION_ADDRESS = ''
