FROM python:3.14.2-trixie

WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock* ./

RUN pip install --no-cache-dir -e .

COPY src ./src

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.runners"]
