[project]
name = "tradebox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "robin-stocks>=3.4.0",
    "textual>=6.11.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "textual-dev>=1.8.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
