API_VERIFICATION_DEFAULT_KEYSETS = {
    "get_portfolio_profile": {
        "url": "https://api.robinhood.com/portfolios/5QU45833/",
        "account": "https://api.robinhood.com/accounts/5QU45833/",
        "start_date": "2015-12-09",
        "market_value": "0.0000",
        "equity": "1979.7400",
        "extended_hours_market_value": "0.0000",
        "extended_hours_equity": "1979.7400",
        "extended_hours_portfolio_equity": "1979.7400",
        "last_core_market_value": "0.0000",
        "last_core_equity": "1979.7400",
        "last_core_portfolio_equity": "1979.7400",
        "excess_margin": "None",
        "excess_maintenance": "None",
        "excess_margin_with_uncleared_deposits": "None",
        "excess_maintenance_with_uncleared_deposits": "None",
        "equity_previous_close": "815.7000",
        "portfolio_equity_previous_close": "815.7000",
        "adjusted_equity_previous_close": "815.7000",
        "adjusted_portfolio_equity_previous_close": "815.7000",
        "withdrawable_amount": "0.22",
        "unwithdrawable_deposits": "0.0000",
        "unwithdrawable_grants": "0.0000",
        "is_primary_account": "True",
        "non_usd_currency_equity": "0.0000",
    },
    "get_open_option_positions": {
