DATABASE_TABLES = {
	"runners": {
        "runner_name_pk": "VARCHAR(255) PRIMARY KEY",
        "active": "BOOLEAN",
        "adjusted_interval": "INTEGER",
        "default_interval": "INTEGER",
        "current_update_success": "BOOLEAN",
        "previous_update_success": "BOOLEAN",
        "epoch_time_previous_success": "NUMERIC",
    },

    "open_option_positions": {
        "position_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
        "local_id": "SMALLSERIAL",
    },

    "open_option_positions_market_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "open_option_positions_instrument_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "open_broker_option_orders": {
        "order_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
        "local_id": "SMALLSERIAL",
    },

    "open_broker_option_orders_market_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "open_broker_option_orders_instrument_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "trigger_option_orders": {
        "order_id_pk": "SMALLSERIAL PRIMARY KEY",
        "active": "BOOLEAN",
        "epoch_time_created_at": "NUMERIC",
        "executed": "BOOLEAN DEFAULT FALSE",
        "execute_only_after_trigger_order_ids": "INTEGER[]",
        "execute_only_after_bracket_order_ids": "INTEGER[]",
        "execute_only_after_trailing_order_ids": "INTEGER[]",
        "execution_deactivates_trigger_order_ids": "INTEGER[]",
        "execution_deactivates_bracket_order_ids": "INTEGER[]",
        "execution_deactivates_trailing_order_ids": "INTEGER[]",
        "buy_or_sell": "TEXT",
        "credit_or_debit": "TEXT",
        "symbol": "TEXT",
        "strike": "NUMERIC",
        "call_or_put": "TEXT",
        "expiration_date": "TEXT",
        "robinhood_option_uuid": "TEXT",
        "quantity": "INTEGER",
        "message_on_success": "TEXT",
        "message_on_failure": "TEXT",
        "below_tick": "NUMERIC",
        "above_tick": "NUMERIC",
        "cutoff_price": "NUMERIC",
        "max_mark_order_attempts": "INTEGER",
        "max_spread_order_attempts": "INTEGER",
        "emergency_order_fill_on_failure": "BOOLEAN",
        "trigger_order_uuid": "UUID",
        "last_monitor_update_epoch_time": "NUMERIC",
    },

    "trigger_option_orders_market_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "trigger_option_orders_instrument_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "bracket_sell_option_orders": {
        "order_id_pk": "SMALLSERIAL PRIMARY KEY",
        "active": "BOOLEAN",
        "epoch_time_created_at": "NUMERIC",
        "executed": "BOOLEAN DEFAULT FALSE",
        "execute_only_after_trigger_order_ids": "INTEGER[]",
        "execute_only_after_bracket_order_ids": "INTEGER[]",
        "execute_only_after_trailing_order_ids": "INTEGER[]",
        "execution_deactivates_trigger_order_ids": "INTEGER[]",
        "execution_deactivates_bracket_order_ids": "INTEGER[]",
        "execution_deactivates_trailing_order_ids": "INTEGER[]",
        "symbol": "TEXT",
        "strike": "NUMERIC",
        "call_or_put": "TEXT",
        "expiration_date": "TEXT",
        "robinhood_option_uuid": "TEXT",
        "quantity": "INTEGER",
        "high_sell_mark_price": "NUMERIC",
        "low_sell_mark_price": "NUMERIC",
        "message_on_success": "TEXT",
        "message_on_failure": "TEXT",
        "below_tick": "NUMERIC",
        "above_tick": "NUMERIC",
        "cutoff_price": "NUMERIC",
        "max_mark_order_attempts": "INTEGER",
        "max_spread_order_attempts": "INTEGER",
        "emergency_order_fill_on_failure": "BOOLEAN",
        "last_monitor_update_epoch_time": "NUMERIC", 
    },

    "bracket_sell_option_orders_market_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "bracket_sell_option_orders_instrument_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "trailing_sell_option_orders": {
        "order_id_pk": "SMALLSERIAL PRIMARY KEY",
        "active": "BOOLEAN",
        "epoch_time_created_at": "NUMERIC",
        "executed": "BOOLEAN DEFAULT FALSE",
        "execute_only_after_trigger_order_ids": "INTEGER[]",
        "execute_only_after_bracket_sell_order_ids": "INTEGER[]",
        "execute_only_after_trailing_sell_order_ids": "INTEGER[]",
        "execution_deactivates_trigger_order_ids": "INTEGER[]",
        "execution_deactivates_bracket_sell_order_ids": "INTEGER[]",
        "execution_deactivates_trailing_sell_order_ids": "INTEGER[]",
        "quantity": "INTEGER",
        "symbol": "TEXT",
        "call_or_put": "TEXT",
        "expiration_date": "TEXT",
        "strike": "NUMERIC",
        "below_tick": "NUMERIC",
        "above_tick": "NUMERIC",
        "cutoff_price": "NUMERIC",
        "robinhood_option_uuid": "TEXT",
        "message_on_success": "TEXT",
        "message_on_failure": "TEXT",
        "max_mark_order_attempts": "INTEGER",
        "max_spread_order_attempts": "INTEGER",
        "emergency_order_fill_on_failure": "BOOLEAN", 
        "percent_from_high_sell_trigger": "NUMERIC",
        "sell_at_specific_price": "NUMERIC",
        "highest_price_since_order_placed": "NUMERIC",
        "purchase_price": "NUMERIC",
        "last_monitor_update_epoch_time": "NUMERIC",
    },

    "trailing_sell_option_orders_market_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "trailing_sell_option_orders_instrument_data": {
        "option_uuid_pk": "VARCHAR(255) PRIMARY KEY",
        "json_data": "JSONB",
        "still_alive": "BOOLEAN",
        "last_update_epoch_time": "NUMERIC",
    },

    "portfolio_profile": {
        "single_id": "INTEGER PRIMARY KEY",
        "json_data": "JSONB",
        "last_update_epoch_time": "NUMERIC",
    },
}

