FROM nginx:1.29.4-trixie-perl

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Create directories for certbot and logs
RUN mkdir -p /var/www/certbot /var/log/nginx

EXPOSE 80 443 8898

CMD ["nginx", "-g", "daemon off;"]
