services:
  postgres:
    image: postgres@sha256:bfe50b2b0ddd9b55eadedd066fe24c7c6fe06626185b73358c480ea37868024d #postgres:18.1-trixie
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"


  # runners:
  #   build: .
  #   container_name: tradebox_runners
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://${DB_USER:-tradebox}:${DB_PASSWORD:-tradebox_password}@postgres:5432/${DB_NAME:-tradebox}
  #     ROBINHOOD_USERNAME: ${ROBINHOOD_USERNAME}
  #     ROBINHOOD_PASSWORD: ${ROBINHOOD_PASSWORD}
  #     PUSHOVER_USER_TOKEN: ${PUSHOVER_USER_TOKEN}
  #     PUSHOVER_API_TOKEN: ${PUSHOVER_API_TOKEN}
  #     MARKET_DATA_REFRESH_INTERVAL: ${MARKET_DATA_REFRESH_INTERVAL:-5}
  #     OPEN_POSITIONS_REFRESH_INTERVAL: ${OPEN_POSITIONS_REFRESH_INTERVAL:-5}
  #     BROKER_ORDERS_REFRESH_INTERVAL: ${BROKER_ORDERS_REFRESH_INTERVAL:-30}
  #     MAXIMUM_INTERVAL: ${MAXIMUM_INTERVAL:-3}
  #     LOG_LEVEL: ${LOG_LEVEL:-INFO}
  #     FILE_LOGGING: ${FILE_LOGGING:-1}
  #     STDOUT_LOGGING: ${STDOUT_LOGGING:-1}
  #   volumes:
  #     - ./logs:/app/logs
  #   restart: unless-stopped

  # wsgi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.wsgi
  #   container_name: tradebox_wsgi
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://${DB_USER:-tradebox}:${DB_PASSWORD:-tradebox_password}@postgres:5432/${DB_NAME:-tradebox}
  #     ROBINHOOD_USERNAME: ${ROBINHOOD_USERNAME}
  #     ROBINHOOD_PASSWORD: ${ROBINHOOD_PASSWORD}
  #     PUSHOVER_USER_TOKEN: ${PUSHOVER_USER_TOKEN}
  #     PUSHOVER_API_TOKEN: ${PUSHOVER_API_TOKEN}
  #     LOG_LEVEL: ${LOG_LEVEL:-INFO}
  #     FILE_LOGGING: ${FILE_LOGGING:-1}
  #     STDOUT_LOGGING: ${STDOUT_LOGGING:-1}
  #   volumes:
  #     - ./logs:/app/logs
  #   restart: unless-stopped
  #   expose:
  #     - "8000"

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   container_name: tradebox_nginx
  #   depends_on:
  #     - wsgi
  #   environment:
  #     DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
  #   ports:
  #     - "${NGINX_DEV_PORT:-8898}:8898"
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ${SSL_CERT_DIR:-./certs}:/etc/letsencrypt:ro
  #     - ./certbot_www:/var/www/certbot:ro
  #     - ./logs/nginx:/var/log/nginx
  #   restart: unless-stopped

# volumes:
#   postgres_data:
